FROM shane/devtools-nix:core-xenial

#RUN nix-env --install \
#      mercurial \
# && docker-nix-cleanup

RUN python3 -m venv /devtools/local/py

MAINTAINER Shane Holloway <shane.holloway@ieee.org>
# TO IMAGE shane/devtools-nix:example-xenial
